apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  namespace: notes-app
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: piyusha19/notes-app
        ports:
        - containerPort: 8000

#Output:

kubectl apply -f deployment.yml 
deployment.apps/notes-app-deployment created

kubectl get pods -n notes-app
NAME                                    READY   STATUS    RESTARTS   AGE
notes-app-deployment-7cfb76d587-28k4m   1/1     Running   0          27s
